server:
  port: '8081'
spring:
  data:
    jpa:
      repositories:
        enabled: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        storage_engine: innodb
        format_sql: 'true'
    database: mysql
    show-sql: 'true'
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: rg.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

